sudo: true
language: node_js
node_js:
  - node
  - '6'
  - '4'
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 15
